---
- name: Create cloud config
  template:
    dest: "{{ openshift.common.config_base }}/cloudprovider/vsphere.conf"
    src: vsphere.conf.j2
  when:
    - openshift_cloudprovider_vsphere_username is defined
    - openshift_cloudprovider_vsphere_password is defined
    - openshift_cloudprovider_vsphere_datacenters is defined
    - openshift_cloudprovider_vsphere_virtualcenters is defined
